### PR TITLE
Optimize Vimeo and showreel loading

### PR DESCRIPTION
**Pull request by raikasdev**
Optimizes front page load by deferring the video and showing the poster from the start (currently it requires the iframe, otherwise it will be 0x0px). Video is only loaded after load (requestIdleCallback) and only if user scrolls to the player. It also fixes the gap without a video or poster on the front page.

These videos aren't using simulated networks, just my internet right now :upside_down_face: 

**Current behavior**

https://github.com/user-attachments/assets/f3222524-7ca0-4dc2-91e9-b68c8a37371f

**With proposed changes**

https://github.com/user-attachments/assets/c4e7c73e-60b0-4241-a176-e4748cdf804e

### CODE REVIEW

**Comment by ronilaukkarinen** [comment]
Tested it through. For me this causes the front page button not to work when I first arrive to a single blog post like https://dude.test/woocommerce-verkkokauppa-mallia-custom-chopper and then click the logo to front page. Swup needs Vimeo and all triggers to be loaded at all times, otherwise those won't exist when we move to a page they are needed.

**Comment by raikasdev** [comment]
Fixed this by utilizing `data-src`on place of `src` on pages that don't need video. Then on swup content replace check for video players and if so, replace data-src with src to iniate script load.

**Comment by ronilaukkarinen** [comment]
Works like charm! Thanks @raikasdev for this! :heart:

**Comment by ronilaukkarinen** [comment]
Should have tested this more thoroughly, but no videos will play or no triggers will work because of this PR, when you land to a page that doesn't have any videos. For example

1. Land as first page and first visit ever on https://www.dude.fi/toitamme
2. Go to front page via logo
3. Can't play videos or see autoplay videos

We need to carry all Vimeo stuff despite the page we're on, otherwise videos won't unless you go on front page or a page with video FIRST.

**Comment by raikasdev** [comment]
> Should have tested this more thoroughly, but no videos will play or no triggers will work because of this PR, when you land to a page that doesn't have any videos. For example
> 
> 1. Land as first page and first visit ever on https://www.dude.fi/toitamme
> 2. Go to front page via logo
> 3. Can't play videos or see autoplay videos
> 
> We need to carry all Vimeo stuff despite the page we're on, otherwise videos won't unless you go on front page or a page with video FIRST.

Hmm, this was addressed in this commit (see front-end.js changes):

https://github.com/digitoimistodude/dude/commit/3644796a39c647e7f3087ffd40a776e3cc91f26e

It should add the vimeo script on reload if the new page has videos :thinking:

**Comment by ronilaukkarinen** [comment]
> It should add the vimeo script on reload if the new page has videos 🤔

For some reason it didn't work at all. As I don't have time to investigate I had to revert :/

**Pull request merged**
